import { db,id,goalSchedule,Goal } from "./store.js";
import { allocateDeposit } from "../scoring/allocation.js";
import { calculateFeatures,calculateKikobaScore } from "../scoring/engine.js";
import { classifyProfile } from "../scoring/profile.js";

const slug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9_]/g,"").slice(0,20)||"member";
export function createUser(name:string,email:string){let base=slug(name),username=base,n=1;while([...db.users.values()].some(u=>u.username.toLowerCase()===username.toLowerCase()))username=`${base}${++n}`;const u={id:id(),name,username,email,createdAt:new Date()};db.users.set(u.id,u);return u}
export function updateUsername(userId:string,username:string){const u=db.users.get(userId);if(!u)throw new Error("USER_NOT_FOUND");const clean=slug(username);if(clean.length<3)throw new Error("USERNAME_TOO_SHORT");if([...db.users.values()].some(x=>x.id!==userId&&x.username.toLowerCase()===clean.toLowerCase()))throw new Error("USERNAME_TAKEN");u.username=clean;return u}
export function createGoal(input:any){const g:Goal={id:id(),userId:input.userId,name:input.name,targetAmount:input.targetAmount,targetDate:input.targetDate?new Date(input.targetDate):undefined,expectedAmount:input.expectedAmount,frequency:input.frequency,priority:input.priority??"NORMAL",status:"ACTIVE",createdAt:new Date()};db.goals.set(g.id,g);goalSchedule(g);return g}
export function userScore(userId:string){const contributions=[...db.contributions.values()].filter(c=>c.userId===userId);const goals=[...db.goals.values()].filter(g=>g.userId===userId);const completed=goals.filter(g=>g.status==="COMPLETED").length;const deposits=[...db.deposits.values()].filter(d=>d.userId===userId);const monthlySavings=deposits.map(d=>d.amount);let streak=0;for(const c of [...contributions].sort((a,b)=>b.dueDate.getTime()-a.dueDate.getTime())){if(c.amountPaid>=c.expectedAmount)streak++;else break}const perf=(arr:any[])=>arr.length?arr.filter(c=>c.amountPaid>=c.expectedAmount).length/arr.length:0;const recent=perf(contributions.slice(-6)),previous=perf(contributions.slice(0,-6));const active=goals.filter(g=>g.status==="ACTIVE").reduce((s,g)=>s+(g.frequency==="WEEKLY"?g.expectedAmount*4.33:g.expectedAmount),0);const features=calculateFeatures({contributions,matureGoals:goals.length,completedGoals:completed,currentStreak:streak,activeMonthlyCommitment:active,monthlySavings,recentPerformance:recent,previousPerformance:previous,meaningfulEvents:deposits.length});const score=calculateKikobaScore(features);const profile=classifyProfile(features,contributions.some(c=>c.status==="MISSED"||c.status==="RECOVERED"));const result={score,confidence:features.confidence,profile,features,calculatedAt:new Date()};const history=db.scores.get(userId)??[];history.push(result);db.scores.set(userId,history);return result}
export function makeDeposit(userId:string,amount:number,goalId?:string){const deposit={id:id(),userId,amount,goalId,createdAt:new Date()};db.deposits.set(deposit.id,deposit);const commitments=[...db.contributions.values()].filter(c=>c.userId===userId).map(c=>({...c,recoveryEligible:c.status==="MISSED",priority:(db.goals.get(c.goalId)?.priority??"NORMAL") as any}));const result=allocateDeposit({amount,now:new Date(),mode:goalId?"EXPLICIT":"AUTO_ALLOCATE",destinationGoalId:goalId,commitments});for(const a of result.allocations){const c=db.contributions.get(a.contributionId)!;const wasMissed=c.status==="MISSED";c.amountPaid+=a.amount;if(c.amountPaid>=c.expectedAmount){c.completedAt=new Date();c.status=wasMissed?"RECOVERED":c.completedAt<=c.dueDate?"ON_TIME":c.completedAt<=c.gracePeriodEnd?"GRACE":"LATE";if(wasMissed)c.recoveredAt=new Date()}else c.status="PARTIAL"}return {deposit,allocation:result,score:userScore(userId)}}
export function dashboard(userId:string){const goals=[...db.goals.values()].filter(g=>g.userId===userId);const deposits=[...db.deposits.values()].filter(d=>d.userId===userId);const score=userScore(userId);return {user:db.users.get(userId),score,goals:goals.map(g=>{const saved=[...db.contributions.values()].filter(c=>c.goalId===g.id).reduce((s,c)=>s+c.amountPaid,0);return {...g,saved,progress:Math.min(1,saved/g.targetAmount)}}),totalSaved:deposits.reduce((s,d)=>s+d.amount,0),recentDeposits:deposits.slice(-10)}}