import "dotenv/config";
import express from "express";
import { z } from "zod";
import { db } from "./app/store.js";
import { createGoal, makeDeposit, dashboard, userScore } from "./app/service.js";
import { prisma } from "./app/prisma.js";

export const app=express();app.use(express.json());app.use(express.static("public"));
const asyncRoute=(fn:any)=>(req:any,res:any,next:any)=>Promise.resolve(fn(req,res,next)).catch(next);
const tiers=["Building","Growing","Reliable","Established","Elite"] as const;type Tier=(typeof tiers)[number];
const tier=(score:number):Tier=>score>=850?"Elite":score>=700?"Established":score>=500?"Reliable":score>=250?"Growing":"Building";
const userExists=async(id:string)=>!!(await prisma.user.findUnique({where:{id},select:{id:true}}));
const uniqueUsername=async(name:string)=>{const base=name.toLowerCase().replace(/[^a-z0-9_]/g,"_").replace(/^_+|_+$/g,"").slice(0,16)||"user";let candidate=base;let n=1;while(await prisma.user.findUnique({where:{username:candidate}})){candidate=`${base.slice(0,Math.max(1,20-String(n).length)}${n++}`;}return candidate;};
const chamaView=(c:any,userId="")=>{const active=c.members.filter((m:any)=>m.status==="ACTIVE");return {...c,members:active.map((m:any)=>m.user),joined:active.some((m:any)=>m.userId===userId),open:active.length<c.maxMembers,memberIds:active.map((m:any)=>m.userId)};};

app.get("/health",(_req,res)=>res.json({ok:true,service:"kikoba"}));

app.post("/v1/auth/register",asyncRoute(async(req:any,res:any)=>{const b=z.object({name:z.string().trim().min(2),email:z.string().email()}).parse(req.body);const existing=await prisma.user.findUnique({where:{email:b.email}});if(existing)return res.status(409).json({error:"EMAIL_EXISTS"});const username=await uniqueUsername(b.name);const user=await prisma.user.create({data:{name:b.name,email:b.email,username}});res.status(201).json(user);}));
app.patch("/v1/users/:userId/profile",asyncRoute(async(req:any,res:any)=>{const b=z.object({username:z.string().trim().min(3).max(20).regex(/^[a-zA-Z0-9_]+$/).optional(),name:z.string().trim().min(2).optional(),profilePhotoUrl:z.string().url().nullable().optional()}).parse(req.body);if(!(await userExists(req.params.userId)))return res.status(404).json({error:"USER_NOT_FOUND"});if(b.username){const found=await prisma.user.findUnique({where:{username:b.username}});if(found&&found.id!==req.params.userId)return res.status(409).json({error:"USERNAME_TAKEN"});}res.json(await prisma.user.update({where:{id:req.params.userId},data:b}));}));
app.get("/v1/users/search",asyncRoute(async(req,res)=>{const q=String(req.query.q??"").trim();if(!q)return res.json([]);res.json(await prisma.user.findMany({where:{OR:[{name:{contains:q,mode:"insensitive"}},{username:{contains:q,mode:"insensitive"}}]},select:{id:true,name:true,username:true,profilePhotoUrl:true},take:20}));}));

app.get("/v1/users/:userId/dashboard",asyncRoute((req:any,res:any)=>dashboard(req.params.userId).then((x:any)=>res.json(x))));
app.get("/v1/users/:userId/score",asyncRoute((req:any,res:any)=>{const s=userScore(req.params.userId);res.json({...s,tier:tier(s.score)});}));
app.post("/v1/goals",asyncRoute((req:any,res:any)=>{const b=z.object({userId:z.string(),name:z.string().trim().min(2),targetAmount:z.number().positive(),targetDate:z.string().optional(),expectedAmount:z.number().positive(),frequency:z.enum(["WEEKLY","MONTHLY"]),priority:z.enum(["HIGH","NORMAL","LOW"]).optional()}).parse(req.body);res.status(201).json(createGoal(b));}));
app.get("/v1/users/:userId/goals",(req,res)=>res.json([...db.goals.values()].filter(g=>g.userId===req.params.userId)));
app.post("/v1/deposits",asyncRoute((req:any,res:any)=>{const b=z.object({userId:z.string(),amount:z.number().positive(),goalId:z.string().optional()}).parse(req.body);res.status(201).json(makeDeposit(b.userId,b.amount,b.goalId));}));

app.get("/v1/chamas",asyncRoute(async(req,res)=>{const userId=String(req.query.userId??"");const chamas=await prisma.chama.findMany({where:{status:"ACTIVE"},include:{members:{where:{status:"ACTIVE"},include:{user:true}}},orderBy:{createdAt:"desc"}});res.json(chamas.map(c=>chamaView(c,userId)));}));
app.post("/v1/chamas",asyncRoute(async(req:any,res:any)=>{const b=z.object({ownerId:z.string(),name:z.string().trim().min(2),description:z.string().trim().optional(),type:z.enum(["LONG_TERM","SHORT_TERM"]),contribution:z.number().positive(),frequency:z.enum(["WEEKLY","MONTHLY"]),maxMembers:z.number().int().min(2).max(50),minTier:z.enum(tiers),goal:z.string().trim().optional(),memberIds:z.array(z.string()).optional()}).parse(req.body);if(!(await userExists(b.ownerId)))return res.status(404).json({error:"USER_NOT_FOUND"});const requested=[...new Set(b.memberIds??[])].filter(x=>x!==b.ownerId);const valid=await prisma.user.findMany({where:{id:{in:requested}},select:{id:true}});const memberIds=[b.ownerId,...valid.map(x=>x.id)];if(memberIds.length>b.maxMembers)return res.status(400).json({error:"MEMBER_LIMIT"});const c=await prisma.$transaction(async tx=>{const chama=await tx.chama.create({data:{ownerId:b.ownerId,name:b.name,description:b.description,type:b.type,contribution:b.contribution,frequency:b.frequency,maxMembers:b.maxMembers,minTier:b.minTier,goal:b.goal,members:{create:memberIds.map(userId=>({userId,role:userId===b.ownerId?"CREATOR":"MEMBER"}))}}});await tx.conversation.create({data:{chamaId:chama.id,members:{create:memberIds.map(userId=>({userId}))}}});return chama;});const full=await prisma.chama.findUniqueOrThrow({where:{id:c.id},include:{members:{where:{status:"ACTIVE"},include:{user:true}},conversation:true}});res.status(201).json({...chamaView(full,b.ownerId),conversationId:full.conversation?.id});}));
app.get("/v1/users/:userId/chamas",asyncRoute(async(req,res)=>{const rows=await prisma.chama.findMany({where:{members:{some:{userId:req.params.userId,status:"ACTIVE"}}},include:{members:{where:{status:"ACTIVE"},include:{user:true}}},orderBy:{createdAt:"desc"}});res.json(rows.map(c=>chamaView(c,req.params.userId)));}));
app.post("/v1/chamas/:id/join",asyncRoute(async(req:any,res:any)=>{const b=z.object({userId:z.string()}).parse(req.body);const c=await prisma.chama.findUnique({where:{id:req.params.id},include:{members:{where:{status:"ACTIVE"}}}});if(!c)return res.status(404).json({error:"CHAMA_NOT_FOUND"});if(!(await userExists(b.userId)))return res.status(404).json({error:"USER_NOT_FOUND"});if(c.members.some(m=>m.userId===b.userId))return res.json({alreadyMember:true});if(c.members.length>=c.maxMembers)return res.status(409).json({error:"CHAMA_FULL"});const s=userScore(b.userId);if(tiers.indexOf(tier(s.score))<tiers.indexOf(c.minTier as Tier))return res.status(403).json({error:"TIER_TOO_LOW",required:c.minTier});await prisma.$transaction(async tx=>{await tx.chamaMember.create({data:{chamaId:c.id,userId:b.userId}});const conv=await tx.conversation.findUnique({where:{chamaId:c.id}});if(conv)await tx.conversationMember.create({data:{conversationId:conv.id,userId:b.userId}});});res.json({joined:true,chamaId:c.id});}));
app.get("/v1/chamas/match",asyncRoute(async(req,res)=>{const userId=String(req.query.userId??"");if(!(await userExists(userId)))return res.status(404).json({error:"USER_NOT_FOUND"});const userTier=tier(userScore(userId).score),rank=tiers.indexOf(userTier);const rows=await prisma.chama.findMany({where:{status:"ACTIVE",members:{none:{userId,status:"ACTIVE"}}},include:{members:{where:{status:"ACTIVE"},include:{user:true}}}});const matches=rows.filter(c=>c.members.length<c.maxMembers&&tiers.indexOf(c.minTier as Tier)<=rank).map(c=>({...chamaView(c,userId),matchScore:Math.min(99,70+(c.frequency==="WEEKLY"?8:4)+(c.members.length>1?8:0))})).sort((a,b)=>b.matchScore-a.matchScore);res.json({tier:userTier,matches});}));

app.get("/v1/users/:userId/friends",asyncRoute(async(req,res)=>{const rows=await prisma.friendship.findMany({where:{OR:[{userAId:req.params.userId},{userBId:req.params.userId}]},include:{userA:true,userB:true}});res.json(rows.map(r=>r.userAId===req.params.userId?r.userB:r.userA));}));
app.post("/v1/friend-requests",asyncRoute(async(req:any,res:any)=>{const b=z.object({fromId:z.string(),toId:z.string()}).parse(req.body);if(b.fromId===b.toId||!(await userExists(b.fromId))||!(await userExists(b.toId)))return res.status(400).json({error:"INVALID_REQUEST"});const existing=await prisma.friendRequest.findFirst({where:{status:"PENDING",OR:[{fromId:b.fromId,toId:b.toId},{fromId:b.toId,toId:b.fromId}]}});if(existing)return res.status(409).json({error:"REQUEST_EXISTS"});res.status(201).json(await prisma.friendRequest.create({data:b}));}));
app.get("/v1/users/:userId/friend-requests",asyncRoute(async(req,res)=>res.json(await prisma.friendRequest.findMany({where:{toId:req.params.userId,status:"PENDING"},include:{from:{select:{id:true,name:true,username:true,profilePhotoUrl:true}}},orderBy:{createdAt:"desc"}}))));
app.post("/v1/friend-requests/:id/respond",asyncRoute(async(req:any,res:any)=>{const b=z.object({userId:z.string(),accept:z.boolean()}).parse(req.body);const r=await prisma.friendRequest.findUnique({where:{id:req.params.id}});if(!r||r.toId!==b.userId||r.status!=="PENDING")return res.status(404).json({error:"REQUEST_NOT_FOUND"});await prisma.$transaction(async tx=>{await tx.friendRequest.update({where:{id:r.id},data:{status:b.accept?"ACCEPTED":"DECLINED"}});if(b.accept){const [a,bb]=[r.fromId,r.toId].sort();await tx.friendship.upsert({where:{userAId_userBId:{userAId:a,userBId:bb}},update:{},create:{userAId:a,userBId:bb}});}});res.json({id:r.id,status:b.accept?"ACCEPTED":"DECLINED"});}));

app.get("/v1/chamas/:id/messages",asyncRoute(async(req,res)=>{const conv=await prisma.conversation.findUnique({where:{chamaId:req.params.id}});if(!conv)return res.json([]);const messages=await prisma.message.findMany({where:{conversationId:conv.id},include:{sender:{select:{id:true,name:true,username:true,profilePhotoUrl:true}}},orderBy:{createdAt:"asc"},take:50});res.json(messages);}));
app.post("/v1/chamas/:id/messages",asyncRoute(async(req:any,res:any)=>{const b=z.object({senderId:z.string(),body:z.string().trim().min(1).max(1000)}).parse(req.body);const conv=await prisma.conversation.findUnique({where:{chamaId:req.params.id},include:{members:true}});if(!conv||!conv.members.some(m=>m.userId===b.senderId))return res.status(403).json({error:"NOT_CHAMA_MEMBER"});res.status(201).json(await prisma.message.create({data:{conversationId:conv.id,senderId:b.senderId,body:b.body},include:{sender:{select:{id:true,name:true,username:true,profilePhotoUrl:true}}}}));}));

app.use((err:any,_req:any,res:any,_next:any)=>{if(err instanceof z.ZodError)return res.status(400).json({error:"VALIDATION_ERROR",message:err.issues.map((i:any)=>i.message).join(". "),details:err.issues});if(err?.code==="P2002")return res.status(409).json({error:"CONFLICT"});console.error(err);res.status(500).json({error:"INTERNAL_ERROR"});});
if(process.env.VERCEL!=="1")app.listen(process.env.PORT||3000,()=>console.log("Kikoba API listening"));